title: moonlight software
description: My Personal Blog
author: Moonlight Software
logo: http://www.toxel.com/wp-content/uploads/2014/12/moonlamp02.jpg
github: https://github.com/moonlight-software
about: Freelance developer
disqus_shortname: aboutashu
google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: developer
      url: /developer/
      icon: fa-users
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Github
      url: https://github.com/moonlight-software
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed

social:
    - icon: fa-facebook
      link: 'https://www.facebook.com/groups/584065201763231/585678301601921/?notif_t=group_activity&notif_id=1467191651671589'
    - icon: fa-skype
      link: 'https://www.facebook.com/sharer/sharer.php?sdk=joey&u=#%2F&display=popup&ref=plugin&src=share_button'
    - icon: fa-twitter
      link: '#'
#    - icon: fa-linkedin
#      link: '#'
#    - icon: fa-stack-exchange
#      link: "https://www.facebook.com/sharer.php?p[url]='http://moonlight-software.github.io/'"


share:
  - icon: fa-stack-exchange
    link: "https://www.facebook.com/sharer.php?p[url]='http://moonlight-software.github.io/'"

#enableTags: true
#tagarray: []

#url: "http://aboutashu.com/hcz-jekyll-blog"
#baseurl: "/hcz-jekyll-blog"
#paginate: 20
#per_page: 20
#paginate_path: "/page:num/"
#markdown: kramdown
#gems:
#  - jekyll-paginate
#  - jekyll-gist
